### ISSUE TITLE
cudatoolkit=9.0 not working with cupy-cuda90 without manual path specification

### ISSUE THREAD

**Issue by berceanu** [fbpic/fbpic#371]
Following the install instructions, when running `fbpic`, I get

```
RuntimeError: Failed to auto-detect CUDA root directory. Please specify `CUDA_PATH` environment variable if you are using CUDA v9.0, v9.1 or versions not yet supported by CuPy.
```
I installed `cudatoolkit=9.0` via `conda` and then `pip install cupy-cuda90`

**Comment by RemiLehe** [comment]
Thanks for reporting this issue!
In order to debug this, could you let us know on which environment you got this error (e.g. Linux, Windows ; remote cluster, maybe)?

**Comment by berceanu** [comment]
Ubuntu 18.04

**Comment by RemiLehe** [comment]
OK, thanks. When looking into it a bit more, it seems that your issue could probably be fixed by adding to your `.bashrc`
```
export CUDA_PATH=$HOME/miniconda3/lib
```
or 
```
export CUDA_PATH=$HOME/anaconda3/lib
```
(depending on whether you used Miniconda or Anaconda)

Could you confirm that this fixes the issue?

**Comment by berceanu** [comment]
That seems to solve the auto-detection issue, but now I get

```
FBPIC (0.13.0)

Running on GPU 

Initializing laser pulse on the mesh...
Done.

Just-In-Time compilation (up to one minute) ...Traceback (most recent call last):
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 242, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_fbpic_script.py", line 120, in <module>
    sim.step(N_step)
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/main.py", line 408, in step
    diag.write( self.iteration )
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/generic_diag.py", line 140, in write
    self.write_hdf5( iteration )
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/field_diag.py", line 85, in write_hdf5
    self.fld.spect2interp('rho_prev')
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/fields/fields.py", line 386, in spect2interp
    self.spect[m].rho_prev, self.interp[m].rho )
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/fields/spectral_transform/spectral_transformer.py", line 108, in spect2interp_scal
    self.fft.inverse_transform( self.spect_buffer_r, interp_array )
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/fbpic/fields/spectral_transform/fourier.py", line 158, in inverse_transform
    cupy.multiply(cupy.asarray(self.buffer1d_out), self.inv_Nz, out=cupy.asarray(self.buffer1d_out))
  File "cupy/core/_kernel.pyx", line 856, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 868, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 630, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 165, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch, name + '.cu')
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 81, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 246, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(10): catastrophic error: cannot open source file "cuda_fp16.h"


1 catastrophic error detected in the compilation of "/tmp/tmpzoenmzsm/deb16c51015044acba1da1ca78da4fea_2.cubin.cu".
Compilation terminated.
```

Here is the [input script](https://gist.github.com/berceanu/9aac7cf6807b431585eaf4eb681b635a)

**Comment by RemiLehe** [comment]
Alright, yes, it seems that for cuda 9.2 and higher, `pip install cupy-cudaXX` ships a fully-working cuda installation, whereas for version cuda 9.0 and 9.1, it seems that `cupy` needs to find it somewhere on your system. Apparently `cudatoolkit` from `conda` does not fit the requirements for this...

Anyway I think that upgrading your GPU driver (whenever possible), so that it supports cuda 9.2 and higher, is the best solution. Therefore, I'll close the issue.
