### ISSUE TITLE
Cuda error: invalid device (CUDA_ERROR_INVALID_DEVICE)

### ISSUE THREAD

**Issue by abonatto** [fbpic/fbpic#418]
Dear FBPIC developers,

In some of my job submissions in the GPU cluster I am using , I am experiencing the following error:

```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    from fbpic.main import Simulation
  File ".../fbpic/lib/python2.7/site-packages/fbpic/main.py", line 20, in <module>
    mpi_select_gpus( MPI )
  File ".../fbpic/lib/python2.7/site-packages/fbpic/utils/cuda.py", line 143, in mpi_select_gpus
    cuda.select_device(i_gpu)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/api.py", line 302, in select_device
    context = devices.get_context(device_id)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/devices.py", line 194, in get_context
    return _runtime.get_or_create_context(devnum)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/devices.py", line 162, in get_or_create_context
    return self.push_context(self.gpus[devnum])
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/devices.py", line 130, in push_context
    ctx = self._get_or_create_context(gpu)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/devices.py", line 120, in _get_or_create_context
    ctx = gpu.get_primary_context()
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 472, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File ".../fbpic/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [101] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_INVALID_DEVICE
```

After discussing with the cluster support, they pointed out that each "GPU box" in the cluster has four GPUs, listed in CUDA_VISIBLE_DEVICES as 0, 1, 2, and 3. It seems that when the cluster assigns me a value  other than 0, I experience the mentioned error. Do you have any suggestion regarding how to deal with this issue?

Regards,

Alex

**Comment by RemiLehe** [comment]
Thanks for reporting this error! I don't think I have observed this error in the past.

Could you try, on your cluster, the following simple Python code (which does not directly involve FBPIC, but contains the part of FBPIC that seems to cause the observed error):
```
from numba import cuda
from mpi4py import MPI

n_gpus = len(cuda.gpus)
rank = MPI.COMM_WORLD.rank
for i_gpu in range(n_gpus):
    if rank%n_gpus == i_gpu:
        cuda.select_device(i_gpu)
    MPI.COMM_WORLD.barrier()
```
More specifically, when saving the above code in a file `test.py`, could you try to run `mpirun -np <N> test.py` on your cluster (where `<N>` should be replaced by the typical number of MPI ranks for which you do observe the bug with FBPIC).

When doing the above test, do you observe the same bug?

**Comment by abonatto** [comment]
Hi Remi, thanks for your support! 

For most of the submitted jobs I get GPU #0, and I never had the error for such cases. When discussing the problem with the cluster support, they observed that GPU #1 was assigned for the cases in which the error was observed. Given that the error is related to selecting a valid CUDA device, and that for sure a GPU is available when it happens, they suggested that selecting a GPU other than #0 could be causing the problem.

However, yesterday I got GPU #1, but I was able to run a job without the error. Moreover, when testing your code today, despite having GPU #2 assigned, I had no errors (both your code and the job ran properly). Therefore, it seems that this is not the cause of the error. 

 I will keep your test code and, as soon as I experience the error again, I will use it and let you know the outcome. Meanwhile, would you have any additional suggestion?

Cheers,

Alex

**Comment by RemiLehe** [comment]
Hey,
Sorry, no other suggestion comes to mind.
You can let us know if this happens again and maybe we can try to understand why.

Best,

Remi

**Comment by abonatto** [comment]
Sure. Again, thanks for your support!

Cheers,

Alex

**Comment by plasmahomie** [comment]
Hi developers,

I would like to reopen this issue as I have had the exact same error when running fbpic on gpus on a cluster, both when running an fbpic simulation and when running the test.py script above. So far I have only had this issue running on the 'gpuplus' partition of my cluster, which uses nVidia H100 GPUs, and not on the 'gpu' partition, which uses nVidia A40 GPUs, if this is maybe relevant. I am currently queued to test this properly on the A40 GPUs and will update with the result.

I have successfully run fbpic several times on both GPU types, so this is an issue that occurs randomly. This would be consistent with the GPU number issue described above.

This is the error I have, identical to above:
```
Traceback (most recent call last):
  File "/mnt/scratch/users/rnr512/fbpic/test.py", line 8, in <module>
    cuda.select_device(i_gpu)
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/api.py", line 437, in select_device
    context = devices.get_context(device_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 144, in get_or_create_context
    return self._activate_context_for(devnum)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/devices.py", line 177, in _activate_context_for
    newctx = gpu.get_primary_context()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 671, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 327, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/users/rnr512/scratch/anaconda3/lib/python3.12/site-packages/numba/cuda/cudadrv/driver.py", line 395, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_UNKNOWN

```
