### ISSUE TITLE
FBPIC checkpoint restart issue with new open-PMD viewer version

### ISSUE THREAD

**Issue by YCAOsz** [fbpic/fbpic#443]
I've got an issue with restarting FBPIC from checkpoint. I started this simulation a few months ago and I used the older version of open-pmd viewer. After I installed the newer version, the FBPIC restart produces an error related to get_particle.  I reinstalled the older version to the conda environment but it doesn't work either. 

Here are the two error outputs: 

FBPIC (0.16.0)

Running on GPU

Initializing laser pulse on the mesh...
Done.

Calculating initial space charge field...
Done.

Warning: File /rds/general/ephemeral/user/yc15818/ephemeral/FBPIC_labconv_022620_042620/FBPIC_labconv_7e23_022620/checkpoints/proc0/hdf5/data03100000.h5 has different openPMD parameters than the rest of the time series.

============================================

        Job resource usage summary

                 Memory (GB)    NCPUs
 Requested  :        24             4
 Used       :         0 (peak)   5.07 (ave)

============================================

Traceback (most recent call last):
  File "/rds/general/user/yc15818/home/Scripts_2ndyr/exec_firstStage/lwfa_022620_7e23_labconverg.py", line 147, in <module>
    restart_from_checkpoint( sim )
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 163, in restart_from_checkpoint
    sim.comm, openpmd_viewer_version )
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 310, in load_species
    ['x', 'y', 'z'], iteration=iteration, species=name )
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/main.py", line 270, in get_particle
    file_handle, species, quantity, self.extensions))
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/data_reader/particle_reader.py", line 57, in read_species_data
    join_infile_path(base_path, particles_path, species) ]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)’

**Comment by YCAOsz** [comment]
This is the error when I still have the newest openpmd version installed. Would it be the case the new checkpoint is corrupted for some reason? Should I delete that one and then it may be fine?Thanks

Traceback (most recent call last):
  File "/rds/general/user/yc15818/home/Scripts_2ndyr/exec_firstStage/lwfa_022620_7e23_labconverg.py", line 147, in <module>
    restart_from_checkpoint( sim )
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 163, in restart_from_checkpoint
    sim.comm, openpmd_viewer_version )
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/fbpic/openpmd_diag/checkpoint_restart.py", line 310, in load_species
    ['x', 'y', 'z'], iteration=iteration, species=name )
  File "/rds/general/user/yc15818/home/.local/lib/python3.6/site-packages/openpmd_viewer/openpmd_timeseries/main.py", line 268, in get_particle
    file_handle, species, quantity, self.extensions))
  File "/rds/general/user/yc15818/home/.local/lib/python3.6/site-packages/openpmd_viewer/openpmd_timeseries/data_reader/particle_reader.py", line 55, in read_species_data
    join_infile_path(base_path, particles_path, species) ]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yc15818/anaconda3/envs/fbpic/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'

**Comment by RemiLehe** [comment]
Thanks for reporting this issue.
Is `data03100000.h5` the last of the checkpoint files? If os, then yes: I think that that particular file has an issue (based on the warning `data03100000.h5 has different openPMD parameters than the rest of the time series.`) and that the easiest solution is to remove it. 
This way, FBPIC will use the last-but-one checkpoint file instead.
