### ISSUE TITLE
cuda- memory overflow.

### ISSUE THREAD

**Issue by samuelmarini** [fbpic/fbpic#625]
Hello,
I have an Nvidia RTX-A4000 graphic card to run FBPIC simulations. However, I need help since when running FBPIC simulations, the graphic card's memory usage constantly increases until it reaches its maximum 16Gb, long before the simulation end. The error I am getting is shown below. I really appreciate any help you can provide. 
Thank you in advance,
Samuel

P.s. I have installed the following packages on my computer:

conda install -c conda-forge cudatoolkit=11.7
pip install cupy-cuda117

===========================================
UserWarning: C:\Users\sm\Anaconda3\lib\site-packages\cupy\_environment.py:213: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
UserWarning: C:\Users\sm\Anaconda3\lib\site-packages\fbpic\utils\cuda.py:210: Failed to detect UUID of GPU 0 (invalid UUID length: 19)
Carrying out the simulation

FBPIC (0.22.0)

Running on GPU

Initializing laser pulse on the mesh...
Done.

|--------                         | 1495/6530, 2:54:37 left, 1963 ms/step
ERROR: GPU reached OUT_OF_MEMORY
(Error occured in fbpic function `add_buffers_gpu`)
Traceback (most recent call last):
File "D:\Simulations\Workspace\tgenerator_06\full_sm_scrip.py", line 321, in <module> sim.step( N_step )
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\main.py", line 442, in step self.comm.exchange_particles(species, fld, self.time)
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\boundaries\boundary_communicator.py", line 748, in exchange_particles self.exchange_particles_aperiodic_subdomain( species, fld, time )
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\boundaries\boundary_communicator.py", line 825, in exchange_particles_aperiodic_subdomain add_buffers_to_particles( species, float_recv_left, float_recv_right,
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\boundaries\particle_buffer_handling.py", line 342, in add_buffers_to_particles add_buffers_gpu( species, float_recv_left, float_recv_right,
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\utils\printing.py", line 326, in g handle_cuda_memory_error( e, f.__name__ )
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\utils\printing.py", line 346, in handle_cuda_memory_error raise( exception )
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\utils\printing.py", line 324, in g return f(*args, **kwargs)
File "C:\Users\sm\Anaconda3\lib\site-packages\fbpic\boundaries\particle_buffer_handling.py", line 466, in add_buffers_gpuparticle_array = cupy.empty( (new_Ntot,), dtype=np.float64)
File "C:\Users\sm\Anaconda3\lib\site-packages\cupy\_creation\basic.py", line 22, in empty return cupy.ndarray(shape, dtype, order=order)
File "cupy\_core\core.pyx", line 136, in cupy._core.core.ndarray.__new__
File "cupy\_core\core.pyx", line 224, in cupy._core.core._ndarray_base._init
File "cupy\cuda\memory.pyx", line 742, in cupy.cuda.memory.alloc
File "cupy\cuda\memory.pyx", line 1419, in cupy.cuda.memory.MemoryPool.malloc
File "cupy\cuda\memory.pyx", line 1440, in cupy.cuda.memory.MemoryPool.malloc
File "cupy\cuda\memory.pyx", line 1120, in cupy.cuda.memory.SingleDeviceMemoryP

**Comment by RemiLehe** [comment]
Thanks for raising the issue.
It is quite common (and expected) for the memory usage to increase during an FBPIC simulation - if you are using a moving window. The reason is that, as the moving window is moving into the plasma, the simulation box gets progressively filled with plasma macroparticles, which do take up quite a bit of GPU memory.

There are unfortunately not many fixes for this problem ; you can either:
- reduce the resolution of the simulation, so that it uses fewer macroparticles
- or use a GPU with more memory (or even several GPUs, with MPI, so that the memory burden is split among them)

Does the above make sense? Do you have any additional questions?

**Comment by samuelmarini** [comment]
Dear Remi Lehe, 
Thank you very much for the excellent answer. As you suggested, reducing the number of macroparticles made the FBPIC simulation via GPU possible. 
Thank you!!!
